# Generated by Django 3.2.3 on 2021-05-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210525_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='first_name',
            new_name='schema_code',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='last_name',
            new_name='schema_name',
        ),
        migrations.AlterField(
            model_name='employees',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
