# Generated by Django 3.2.3 on 2021-05-26 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210526_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='emp_id',
        ),
    ]
